databases:
  - name: blitzapp-db
    plan: free

services:
  - type: web
    name: blitzapp
    env: node
    plan: free
    buildCommand: yarn --frozen-lockfile --prod=false && blitz build && blitz prisma migrate deploy
    startCommand: blitz start
    envVars:
      - key: NODE_ENV
        value: production
      - key: postgres://blitzapp_db_wkng_user:uUwLvlO3kDMvwcxVIHl6n0ZalztaIosR@dpg-cdkj1ida499ekt3o8bc0-a/blitzapp_db_wkng
        fromDatabase:
          name: blitzapp-db
          property: connectionString
      - key: SESSION_SECRET_KEY
        generateValue: true
